### PR TITLE
Add python3-apt dependency for py3-debian-8

### PR DESCRIPTION
**Pull request by waynew**
Fixes salt/#52248

I'm not sure if this is the best/correct place for it, but, I did test it locally and it worked. I only did a converge/verify with py3-debian-8, though.

### CODE REVIEW

**Comment by Ch3LL** [comment]
since this test requires this library can we add a skipif the library is not installed as well?

**Comment by waynew** [comment]
We *could* but my argument against that is that it should really be a failure if the library isn't installed. Do we have a `failIf` or something?

Mainly, I'm worried about the (unlikely) possibility that a breaking change is introduced but the test gets skipped because the library isn't installed.

**Comment by Ch3LL** [comment]
yeah that makes sense. I cant think of something like that, other than if we just add a check in the test and make it fail. I am just looking for a way to make it easier to troubleshoot in the future if the package is not installed. Not really required just a suggestion, we can get this in as is.

**Comment by s0undt3ch** [comment]
Sorry Wayne, I could have been more explicit when you asked.

**Comment by waynew** [comment]
Swap is out (and updated gitignore). 

I'm not *entirely* sure if I agree that it doesn't have anything to do with Python3 - at least, from Debian 8's perspective, `python3-apt` is a required install.

But I'll give that a shot (not sure where the right place is to make this `python/apt.sls` state apply, but I'm hoping that what I've done will work).

**Comment by waynew** [comment]
Hm. Failed when I ran using:

```
bundle exec kitchen destroy py3-debian-8 && bundle exec kitchen converge py3-debian-8 && bundle exec kitchen verify py3-debian-8
```

**Comment by s0undt3ch** [comment]
is this only supposed to go into develop?

**Comment by waynew** [comment]
Oh... no, this should be targeting 2019.2 🤦‍♂️

**Comment by waynew** [comment]
And apparently I should rebase 😛

**Comment by waynew** [comment]
Okay, so now we're targeting the right branch and what-not. But for some reason this doesn't actually install the python apt state :suspect:

**Comment by waynew** [comment]
Okay, after a few false starts, I've got the right place for this, that worked locally 🙂 

✨

**Comment by waynew** [comment]
@s0undt3ch / @Ch3LL should I go ahead and merge this? Or wait until the Travis CI build finishes (successfully)?

**Comment by s0undt3ch** [comment]
How urgent is it?
If not urgent I can merge it in my morning...
If it has finished running.

**Comment by waynew** [comment]
@s0undt3ch that's fine... if it finishes running :trollface: 😂

**Pull request merged**
