### PR TITLE
add states to install virtualbox

### PR DESCRIPTION
**Pull request by Ch3LL**

### CODE REVIEW

**Comment by rallytime** [comment]
@Ch3LL I know it has been a while since you wrote these, but in an effort to clean up some old PRs, I ran this really quickly on a CentOS 7 VM and it looks like some things need to be adjusted here before we can get this in:
```
----------
          ID: install_epel_repo
    Function: pkg.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1746, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 1277, in installed
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pkg.py", line 491, in _find_install_targets
                  cached_path = __salt__['cp.cache_file'](val, saltenv=kwargs['saltenv'])
                File "/usr/lib/python2.7/site-packages/salt/modules/cp.py", line 405, in cache_file
                  result = _client().cache_file(path, saltenv)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 189, in cache_file
                  return self.get_url(path, '', True, saltenv, cachedir=cachedir)
                File "/usr/lib/python2.7/site-packages/salt/fileclient.py", line 636, in get_url
                  raise MinionError('Error: {0} reading {1}'.format(query['error'], url))
              MinionError: Error: HTTP 404: Not Found reading http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
     Started: 17:14:36.680127
    Duration: 663.574 ms
     Changes:
----------
          ID: install_deps
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Running scope as unit run-18233.scope.
                    Loaded plugins: fastestmirror
                    Retrieving key from https://www.virtualbox.org/download/oracle_vbox.asc
                    Importing GPG key 0x98AB5139:
                     Userid     : "Oracle Corporation (VirtualBox archive signing key) <info@virtualbox.org>"
                     Fingerprint: 7b0f ab3a 13b9 0743 5925 d9c9 5442 2a4b 98ab 5139
                     From       : https://www.virtualbox.org/download/oracle_vbox.asc
                    Loading mirror speeds from cached hostfile
                     * base: mirrors.linode.com
                     * epel: mirrors.kernel.org
                     * extras: mirrors.linode.com
                     * updates: mirrors.linode.com
                    No package kernel-PAE-devel available.
                    Error: Nothing to do
     Started: 17:14:37.344137
    Duration: 5069.313 ms
     Changes:
```

I rebased this PR on top of the most recent `master` branch as well, and it looks like some other states that are not related to this change are failing, too. Are you running these states for the cloud tests somewhere and are they working? Namely the `SaltTesting` pip installed state is failing, as well as the pip install for the azure package. I don't know if that rings any bells in some of the cloud-test work you've been doing.

**Comment by rallytime** [comment]
Note that my last comment about the other two states that are unrelated to your changes as failing don't need to be fixed here. More of a question about if these are known issues when running the cloud tests.

**Comment by Ch3LL** [comment]
Yeah sorry its been a while since I have been able to get to this. If we want to close this I am fine with that.

**Comment by rallytime** [comment]
@Ch3LL Ok, no problem. We can open this up again when you're ready to come back to it. :)

**Pull request closed without merging**
