### PR TITLE
Revert openstack changes

### PR DESCRIPTION
**Pull request by rallytime**
The changes that went last week to add openstack configurations to the Jenkins VMs are causing problems with memory usage in our testing VMs. Instead of doubling the size of our test VMs that we're spinning up, we should go a little more slowly with the change.

After discussing this internally, we decided to revert these changes so we could get our tests back online. This PR reverts the changes added by #227 and #229, as well as any of the changes made to fix up any issues those PRs made. I know this PR is painting with a broad revert brush, but there were so many small fixes that have gone into the states that I wanted to get everything back to running as quickly as possible. The other commits that were reverted were #230, #231, #236, #237, #238, and #245. 

There are likely some good changes in here that we may want to reimplement before we address the openstack issues, but I would like to move more slowly with those changes and address them individually.

I tested this PR on Ubuntu 16 and CentOS 7 and both installed the salt-jenkins states successfully.

ping @thatch45 and @cachedout 

@gtmanfred Apologies that we need to revert all of this work that you did. When you get back from PTO perhaps we can make a plan with @thatch45 or @cachedout to make sure we get some openstack tests running somewhere without having to double the memory footprint of our current testing VMs and infrastructure.

### CODE REVIEW

**Comment by thatch45** [comment]
While this is perfectly reasonable for now we need to get the openstack tests up and running ASAP, I should make sure and clarify that this is just a stop gap solution to get the test suite running again. We need to set up the openstack tests to run on a specific platform so we don't hinder the entire test suite.

@gtmanfred these tests are FANTASTIC, we just need to more carefully apply them :)

**Comment by gtmanfred** [comment]
Yup, sounds good!

**Comment by gtmanfred** [comment]
Instead of pulling it all out, can we not just remove openstack from
git.salt?

**Comment by thatch45** [comment]
I think that would be a better approach

**Comment by rallytime** [comment]
I thought about doing that, but I thought that there were places that keystone states were doing other things before the glance/nova changes were made and I wasn't sure what to keep in or not. I could be wrong. Really I was just trying to get jenkins back online so we can move on with the tagging/testing process, but I think removing them from git.salt will be cleaner and easier to fix moving forward.

I will keep this open for now since I know that it works, but I will take another look.

**Comment by rallytime** [comment]
Ok, as long as it's ok to disable the previous keystone states that were in place before the openstack changes were made in the PRs I referenced above, then it's easy to disable the those. I have fixed this in #249. I'll close this one.

**Pull request closed without merging**
