### PR TITLE
Increase volume size to 40G on FreeBSD

### PR DESCRIPTION
**Pull request by krionbsd**

### CODE REVIEW

**Review by bryceml — COMMENTED** [review]
We should do 40G since that's the size that it launches with kitchen.

**Comment by krionbsd** [comment]
> We should do 40G since that's the size that it launches with kitchen.

yes, fixed

**Review by bryceml — COMMENTED** [review]
We also still need the commands to run to grow the filesystem.

gpart, growfs, etc.

**Review by bryceml — APPROVED** [review]

**Review by bryceml — CHANGES_REQUESTED** [review]
we should have a line that errors if it didn't automatically expand to the correct size.  something like `df -h|grep /$|grep 40G` or however you think would work best to check it.

**Comment by krionbsd** [comment]
> we should have a line that errors if it didn't automatically expand to the correct size. something like `df -h|grep /$|grep 40G` or however you think would work best to check it.

I wonder why it shouldn't automatically expand to the correct size, we explicitly set 40G in driver.yml and in freebsd.json

**Comment by bryceml** [comment]
> > we should have a line that errors if it didn't automatically expand to the correct size. something like `df -h|grep /$|grep 40G` or however you think would work best to check it.
> 
> I wonder why it shouldn't automatically expand to the correct size, we explicitly set 40G in driver.yml and in freebsd.json

I wonder that too.  I wonder if for some reason the automatic expansion only happens on the first instance or boot of the freebsd AMI.

**Review by bryceml — APPROVED** [review]

**Review by bryceml — APPROVED** [review]

**Pull request merged**
