### PR TITLE
no need to run tests post merge

### PR DESCRIPTION
**Pull request by logikone**

### CODE REVIEW

**Comment by logikone** [comment]
i closed #1389 and reopened as this one since github didn't send any webhooks for some reason

**Comment by logikone** [comment]
> i closed #1389 and reopened as this one since github didn't send any webhooks for some reason

though now i see that they didn't finally go through heh

**Comment by s0undt3ch** [comment]
I would still like to have builds once merged, because of direct pushes...
But those are scarce, so, if I'm alone on this thought, I'm cool with this getting merged.

**Comment by logikone** [comment]
> I would still like to have builds once merged, because of direct pushes...
> But those are scarce, so, if I'm alone on this thought, I'm cool with this getting merged.

ok, thats cool. I just thought it was redundant to run the same tests all over again for pr after it was merged

**Comment by s0undt3ch** [comment]
This change was merged on another PR

**Pull request closed without merging**
