### PR TITLE
Remove no_show_proc state

### PR DESCRIPTION
**Pull request by KaiSforza**
@gtmanfred

### CODE REVIEW

**Comment by gtmanfred** [comment]
Why are we doing this on 2017.7?

Aren't we trying to troubleshoot why 2018.3 and newer is slow?

**Comment by KaiSforza** [comment]
it was everything that's slow.

**Comment by gtmanfred** [comment]
2017.7 is not, it is an hour to an hour and a half.
screen shot 2018-10-10 at 12 57 40 pm

**Comment by gtmanfred** [comment]
For anyone that comes back to this, 2017.7 is running fine, the only stuff that is more than an hour and a half is mac, which we know about, and opensuse, which is 30 minutes slower because we have to waste a half our updating the 42.3 image at the start of the test run.

py3
screen shot 2018-10-10 at 12 59 55 pm

py2
screen shot 2018-10-10 at 1 00 28 pm

**Pull request closed without merging**
