### PR TITLE
[develop] Cherry Pick GitPython and Locale Changes

### PR DESCRIPTION
**Pull request by Ch3LL**
Cherry pick 001b2eddae5153217c51e3090b9767c9aa01cffa into develop
Cherry pick a54be3bf0e2b06fd41d75cdb2b75d38c23e54310 into develop

### CODE REVIEW

**Comment by bryceml** [comment]
you will likely need the fix for fedora as well

**Comment by bryceml** [comment]
https://github.com/saltstack/salt-jenkins/pull/1454/commits/a54be3bf0e2b06fd41d75cdb2b75d38c23e54310

**Comment by Ch3LL** [comment]
k i'll close this and just do a merge forward

**Comment by bryceml** [comment]
there is a lot of stuff to merge forward that felippe is working on, it will be messy.

**Comment by Ch3LL** [comment]
k i'll just pull in the other change then. thanks for the heads up

**Pull request merged**
