### PR TITLE
Don't install npm and bower on openSUSE

### PR DESCRIPTION
**Pull request by rallytime**

### CODE REVIEW

**Comment by rallytime** [comment]
ping @s0undt3ch and @aboe76 - This should help get openSUSE past the salt-jenkins states with running the test suite.

**Comment by aboe76** [comment]
@rallytime I'm looking closely at the new run 
https://jenkins.saltstack.com/job/salt-linode-opensuse13/1178/

**Comment by aboe76** [comment]
@rallytime at least the build runs and shows errors :)

**Comment by rallytime** [comment]
Indeed. Looks like we have some tests to look at/clean up/debug.

**Comment by aboe76** [comment]
haven't tried to install a specific version via salt on suse, so it could be legit..

**Comment by aboe76** [comment]
@rallytime opensuse 13.2 with salt 2014.7 can install pkgs with a specific version in a state
and multipkgs with versions.. so the test fails on something else:

test muli pkg with version
```
mypkgs:
  pkg.installed:
    - pkgs:
      - lighttpd: 1.4.35-4.1
      - gamin-server
      - libfam0-gamin
      - spawn-fcgi
```
test with single pkg version
```
lighttpd:
  pkg.installed:
    - version: 1.4.35-4.1
    - pkg_verify: True
```

all work.

**Comment by rallytime** [comment]
Yeah I think the test you were watching was on develop. I'll be interested to see if those tests fail on 2015.2 as well: https://jenkins.saltstack.com/view/2015.2%20Branch/job/salt-2015.2-linode-opensuse13/806/console

**Comment by aboe76** [comment]
Let see,

At least I can confirm that a salt-master running develop can talk to 2014.7.2 :)

**Comment by rallytime** [comment]
It might have something to do with the package we're trying to install. I am not sure though. Still investigating.

**Comment by rallytime** [comment]
Also, this bug appears to only be present on develop right now, as the tests for 2015.2 passed.

**Comment by aboe76** [comment]
I see, Finished: SUCCESS, I'm happy to see suse test reports with success..

**Comment by aboe76** [comment]
@rallytime thanks for the time to fix opensuse on jenkins.

**Comment by rallytime** [comment]
Sure! No problem. I'm glad we have these running again. I'll need to do some more debugging to figure out why this is failing on develop, but we'll get it straightened out. Glad it's not happening on a release branch at least, now that we've got the tests running again!

**Pull request merged**
