### PR TITLE
Install libcurl-dev

### PR DESCRIPTION
**Pull request by Ch3LL**
System Requirement for pycurl (being added in this PR https://github.com/saltstack/salt/pull/55831)

### CODE REVIEW

**Comment by Ch3LL** [comment]
ping @bryceml or @s0undt3ch any ideas why im seeing:

```
17:51:02  + inv build-aws --staging --distro=centos --distro-version=7 --salt-branch=master --salt-pr=1630
17:51:02  Couldn't find packer. Please install to proceed.
```

in all the tests?

**Comment by s0undt3ch** [comment]
I'll defer to @bryce

**Comment by bryceml** [comment]
it has been uninstalled from the base image and we install it as part of the process, work has been done in #1620 to do that.  salt-jenkins needs some work, finishing up pull request #1620 should fix a bunch of things we want fixed, but I haven't had time to do it lately.

you should be able to include

https://github.com/saltstack/salt-jenkins-pipeline-libs/blob/master-1.2-golden/vars/buildGoldenImage.groovy#L60-L65

in the .ci files and it should work again.  I can do that do that for you if you want tomorrow.

**Comment by Ch3LL** [comment]
ya i would appreciate that. thanks

**Comment by Ch3LL** [comment]
@dwoz you okay merging this as is? The arch tests are failing because we dont support python 3.8 yet, and I'm investigating the windows failure right now. Its not related to my PR but the upgrade to virtualenv. We can just ensure we do not promote the windows image yet until the test fix is resolved which im working on right now. Going to open a separate PR here soon to try a couple things for the windows issue.

**Pull request merged**
