### PR TITLE
Neon add pr tests

### PR DESCRIPTION
**Pull request by bryceml**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
We don't test against Py3, or did I just looked at the pipeline which doesn't test Py3 

We actually need to test both Py2 and Py3, where applicable...

**Comment by s0undt3ch** [comment]
Perhaps parallelize Py2 and Py3 testing....

**Comment by bryceml** [comment]
yeah, we don't test py3, we could add that.

**Comment by bryceml** [comment]
I think the best way is to finish merging  this forward to develop and then start working on parallelizing running py3 and merging that forward starting with 2017.7 and get that on all applicable branches.

**Pull request merged**
