### PR TITLE
Changing the pypi indexURL to the new one

### PR DESCRIPTION
**Pull request by dubb-b**
This PR is to add the new PyPi proxy repo address as the primary index url.

### CODE REVIEW

**Comment by Ch3LL** [comment]
ping @rallytime can you give this a review ? @dubb-b and I put this together so want to maek sure we aren't missing anything

**Comment by rallytime** [comment]
This looks good to me from some basic testing. However, I am wondering if we want to hold off on this change until we get the next release out the door. Though, if we run into problems we can always revert this quickly.

@Ch3LL I think you were working on the 2016.11 branch for jenkins today. What is your feeling on my question above?

**Comment by dubb-b** [comment]
@rallytime Just as a note, if it has issues it would be no different than what is there now. It would just go back and default to pypi.org.

**Comment by Ch3LL** [comment]
Actually lets wait until we get 2016.11.5 tagged. The only possible issue I see is the packages are not at the same version or something weird. Just to be safe since we are waiting for jenkins tests to pass right now. Ill update here once we are good to go

**Pull request merged**
