### PR TITLE
add kazoo for zookeeper tests

### PR DESCRIPTION
**Pull request by gtmanfred**

### CODE REVIEW

**Comment by s0undt3ch** [comment]
We might need to gate this for non Linux distributions since I believe we only install docker in Linux distributions?

**Comment by s0undt3ch** [comment]
Gate it on `git/salt.sls`

**Comment by gtmanfred** [comment]
It is gated in git.salt to only install with the docker state on centos 7.

**Comment by s0undt3ch** [comment]
Bah! Missed the existing gate.

**Pull request merged**
